# required variables (configure your pipeline to store these)
#   DH_USERNAME: DockerHub username
#   DH_PASSWORD: DockerHub password

sudo: required
language: bash
services:
- docker
before_script:
- docker login -u "${DH_USERNAME}" -p "${DH_PASSWORD}";
after_script:
- docker logout
script:
# prepare Makefile.properties
- echo "DOCKERUSER=myuser" > Makefile.properties
- echo "DOCKERREGISTRY=docker.io" >> Makefile.properties
# check if example works
- make test.example 
# run the build/publish, see Makefile for more info
- make publish