sudo: required
language: bash
services:
- docker
stages:
- build
before_script:
- docker login -u "${DH_USERNAME}" -p "${DH_PASSWORD}";
after_script:
- docker logout
jobs:
  include:
  - stage: build
    if: branch = master
    env:
    - IMAGE_NAME: go
    script:
    - ./build.sh "${DH_REPO}" "${IMAGE_NAME}" "./go";
    - COMMIT_MESSAGE="${TRAVIS_COMMIT_MESSAGE}" ./publish.sh "${DH_REPO}" "${IMAGE_NAME}";
